### ISSUE TITLE
Specifying multiple dependencies may not be functioning properly

### ISSUE THREAD

**Issue by lal65** [bluehorndigital/setup-drupal#16]
Hey Matt!  Thanks for this wonderful tool.

I'm running into what might be PEBKAC, but on the off-chance that it isn't, I wanted to open an issue.  Here's what I'm trying to run:

```
- name: Setup Drupal action
  uses: bluehorndigital/setup-drupal@v1.0.4
  with:
    version: ${{ matrix.drupal-core }}
    dependencies: 'drupal/coder:=8.3.13 drupal/webform:^6.0'
```

and here's what I get:

```
Could not parse version constraint drupal/webform:^6.0: Invalid version string "drupal/webform:^6.0"
```

In my case, the webform module is a hard dependency on the module that I'm testing.  Unfortunately, the repository that's acting up is not public (for security reasons, it can't be public yet).

I hope all has been well with you and yours.

**Comment by lal65** [comment]
As a workaround, I _am_ able to do this, however:

```
      - name: Setup Drupal action
        uses: bluehorndigital/setup-drupal@v1.0.4
        with:
          version: ${{ matrix.drupal-core }}
          dependencies: 'drupal/coder:=8.3.13'
      - name: Workaround to install webform module
        run: cd ~/drupal && composer require drupal/webform
```

:+1:
